global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.29.42:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.29.42:9090']
